services:
  dashboard:
    build: .
    container_name: aviation_dashboard
    ports:
      - "8050:8050"
    volumes:
      - ./data:/AnalisiIncidentiAerei/data
      - ./logs:/AnalisiIncidentiAerei/logs
    restart: unless-stopped
